//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceMESproPanelWs
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wms_get_finish_pro_panel_interface_impl.wms_get_finish_pro_panel_interface" +
        ".webservices.calb/", ConfigurationName="ServiceReferenceMESproPanelWs.ICalbWmsGetFinshProPanelWebService")]
    public interface ICalbWmsGetFinshProPanelWebService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(wmsIfaceResultVO))]
        System.Threading.Tasks.Task<ServiceReferenceMESproPanelWs.wmsGetFinishProPanelResponse> wmsGetFinishProPanelAsync(ServiceReferenceMESproPanelWs.wmsGetFinishProPanel request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wms_get_finish_pro_panel_interface_impl.wms_get_finish_pro_panel_interface" +
        ".webservices.calb/")]
    public partial class calbProPanelTaryBarCodeVO
    {
        
        private string remarks1Field;
        
        private string remarks2Field;
        
        private string remarks3Field;
        
        private string trayBarcodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string remarks1
        {
            get
            {
                return this.remarks1Field;
            }
            set
            {
                this.remarks1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string remarks2
        {
            get
            {
                return this.remarks2Field;
            }
            set
            {
                this.remarks2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string remarks3
        {
            get
            {
                return this.remarks3Field;
            }
            set
            {
                this.remarks3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string trayBarcode
        {
            get
            {
                return this.trayBarcodeField;
            }
            set
            {
                this.trayBarcodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wms_get_finish_pro_panel_interface_impl.wms_get_finish_pro_panel_interface" +
        ".webservices.calb/")]
    public partial class calbProPanelDetailVO
    {
        
        private string batteryGradeNoField;
        
        private string capacityField;
        
        private string inspectionResultField;
        
        private string kValueField;
        
        private string materialBarcodeField;
        
        private string materialCodeField;
        
        private string materialNameField;
        
        private string ngMessageField;
        
        private string positionNoField;
        
        private string productDateField;
        
        private string productOrderField;
        
        private string productSignField;
        
        private string productionPlanNoField;
        
        private string remarks1Field;
        
        private string remarks2Field;
        
        private string remarks3Field;
        
        private string remarks4Field;
        
        private string resistanceAcField;
        
        private string resistanceDcField;
        
        private string unitCodeField;
        
        private string voltageOcv1Field;
        
        private string voltageOcv2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string batteryGradeNo
        {
            get
            {
                return this.batteryGradeNoField;
            }
            set
            {
                this.batteryGradeNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string capacity
        {
            get
            {
                return this.capacityField;
            }
            set
            {
                this.capacityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string inspectionResult
        {
            get
            {
                return this.inspectionResultField;
            }
            set
            {
                this.inspectionResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string KValue
        {
            get
            {
                return this.kValueField;
            }
            set
            {
                this.kValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string materialBarcode
        {
            get
            {
                return this.materialBarcodeField;
            }
            set
            {
                this.materialBarcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string materialCode
        {
            get
            {
                return this.materialCodeField;
            }
            set
            {
                this.materialCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string materialName
        {
            get
            {
                return this.materialNameField;
            }
            set
            {
                this.materialNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ngMessage
        {
            get
            {
                return this.ngMessageField;
            }
            set
            {
                this.ngMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string positionNo
        {
            get
            {
                return this.positionNoField;
            }
            set
            {
                this.positionNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string productDate
        {
            get
            {
                return this.productDateField;
            }
            set
            {
                this.productDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string productOrder
        {
            get
            {
                return this.productOrderField;
            }
            set
            {
                this.productOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string productSign
        {
            get
            {
                return this.productSignField;
            }
            set
            {
                this.productSignField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string productionPlanNo
        {
            get
            {
                return this.productionPlanNoField;
            }
            set
            {
                this.productionPlanNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string remarks1
        {
            get
            {
                return this.remarks1Field;
            }
            set
            {
                this.remarks1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string remarks2
        {
            get
            {
                return this.remarks2Field;
            }
            set
            {
                this.remarks2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string remarks3
        {
            get
            {
                return this.remarks3Field;
            }
            set
            {
                this.remarks3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string remarks4
        {
            get
            {
                return this.remarks4Field;
            }
            set
            {
                this.remarks4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string resistanceAc
        {
            get
            {
                return this.resistanceAcField;
            }
            set
            {
                this.resistanceAcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string resistanceDc
        {
            get
            {
                return this.resistanceDcField;
            }
            set
            {
                this.resistanceDcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string unitCode
        {
            get
            {
                return this.unitCodeField;
            }
            set
            {
                this.unitCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string voltageOcv1
        {
            get
            {
                return this.voltageOcv1Field;
            }
            set
            {
                this.voltageOcv1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string voltageOcv2
        {
            get
            {
                return this.voltageOcv2Field;
            }
            set
            {
                this.voltageOcv2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wms_get_finish_pro_panel_interface_impl.wms_get_finish_pro_panel_interface" +
        ".webservices.calb/")]
    public partial class calbProPanelDataVO
    {
        
        private calbProPanelDetailVO[] groupDiskDtlListField;
        
        private string remarks1Field;
        
        private string remarks2Field;
        
        private string remarks3Field;
        
        private string remarks4Field;
        
        private string trayBarcodeField;
        
        private string trayTypeNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("groupDiskDtlList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public calbProPanelDetailVO[] groupDiskDtlList
        {
            get
            {
                return this.groupDiskDtlListField;
            }
            set
            {
                this.groupDiskDtlListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string remarks1
        {
            get
            {
                return this.remarks1Field;
            }
            set
            {
                this.remarks1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string remarks2
        {
            get
            {
                return this.remarks2Field;
            }
            set
            {
                this.remarks2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string remarks3
        {
            get
            {
                return this.remarks3Field;
            }
            set
            {
                this.remarks3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string remarks4
        {
            get
            {
                return this.remarks4Field;
            }
            set
            {
                this.remarks4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string trayBarcode
        {
            get
            {
                return this.trayBarcodeField;
            }
            set
            {
                this.trayBarcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string trayTypeNo
        {
            get
            {
                return this.trayTypeNoField;
            }
            set
            {
                this.trayTypeNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(calbProPanelResultVO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wms_get_finish_pro_panel_interface_impl.wms_get_finish_pro_panel_interface" +
        ".webservices.calb/")]
    public partial class wmsIfaceResultVO
    {
        
        private int codeField;
        
        private string messageField;
        
        private string remarks1Field;
        
        private string remarks2Field;
        
        private string remarks3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string remarks1
        {
            get
            {
                return this.remarks1Field;
            }
            set
            {
                this.remarks1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string remarks2
        {
            get
            {
                return this.remarks2Field;
            }
            set
            {
                this.remarks2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string remarks3
        {
            get
            {
                return this.remarks3Field;
            }
            set
            {
                this.remarks3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wms_get_finish_pro_panel_interface_impl.wms_get_finish_pro_panel_interface" +
        ".webservices.calb/")]
    public partial class calbProPanelResultVO : wmsIfaceResultVO
    {
        
        private calbProPanelDataVO dataField;
        
        private string trayBarCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public calbProPanelDataVO data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string trayBarCode
        {
            get
            {
                return this.trayBarCodeField;
            }
            set
            {
                this.trayBarCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wmsGetFinishProPanel", WrapperNamespace="http://wms_get_finish_pro_panel_interface_impl.wms_get_finish_pro_panel_interface" +
        ".webservices.calb/", IsWrapped=true)]
    public partial class wmsGetFinishProPanel
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wms_get_finish_pro_panel_interface_impl.wms_get_finish_pro_panel_interface" +
            ".webservices.calb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReferenceMESproPanelWs.calbProPanelTaryBarCodeVO arg0;
        
        public wmsGetFinishProPanel()
        {
        }
        
        public wmsGetFinishProPanel(ServiceReferenceMESproPanelWs.calbProPanelTaryBarCodeVO arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wmsGetFinishProPanelResponse", WrapperNamespace="http://wms_get_finish_pro_panel_interface_impl.wms_get_finish_pro_panel_interface" +
        ".webservices.calb/", IsWrapped=true)]
    public partial class wmsGetFinishProPanelResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wms_get_finish_pro_panel_interface_impl.wms_get_finish_pro_panel_interface" +
            ".webservices.calb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReferenceMESproPanelWs.calbProPanelResultVO @return;
        
        public wmsGetFinishProPanelResponse()
        {
        }
        
        public wmsGetFinishProPanelResponse(ServiceReferenceMESproPanelWs.calbProPanelResultVO @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ICalbWmsGetFinshProPanelWebServiceChannel : ServiceReferenceMESproPanelWs.ICalbWmsGetFinshProPanelWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class CalbWmsGetFinshProPanelWebServiceClient : System.ServiceModel.ClientBase<ServiceReferenceMESproPanelWs.ICalbWmsGetFinshProPanelWebService>, ServiceReferenceMESproPanelWs.ICalbWmsGetFinshProPanelWebService
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CalbWmsGetFinshProPanelWebServiceClient() : 
                base(CalbWmsGetFinshProPanelWebServiceClient.GetDefaultBinding(), CalbWmsGetFinshProPanelWebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CalbWmsGetFinshProPanelWebServiceImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalbWmsGetFinshProPanelWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CalbWmsGetFinshProPanelWebServiceClient.GetBindingForEndpoint(endpointConfiguration), CalbWmsGetFinshProPanelWebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public CalbWmsGetFinshProPanelWebServiceClient(string remoteAddress) :
base(CalbWmsGetFinshProPanelWebServiceClient.GetDefaultBinding(), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = EndpointConfiguration.CalbWmsGetFinshProPanelWebServiceImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        public CalbWmsGetFinshProPanelWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CalbWmsGetFinshProPanelWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalbWmsGetFinshProPanelWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CalbWmsGetFinshProPanelWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalbWmsGetFinshProPanelWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceMESproPanelWs.wmsGetFinishProPanelResponse> ServiceReferenceMESproPanelWs.ICalbWmsGetFinshProPanelWebService.wmsGetFinishProPanelAsync(ServiceReferenceMESproPanelWs.wmsGetFinishProPanel request)
        {
            return base.Channel.wmsGetFinishProPanelAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMESproPanelWs.wmsGetFinishProPanelResponse> wmsGetFinishProPanelAsync(ServiceReferenceMESproPanelWs.calbProPanelTaryBarCodeVO arg0)
        {
            ServiceReferenceMESproPanelWs.wmsGetFinishProPanel inValue = new ServiceReferenceMESproPanelWs.wmsGetFinishProPanel();
            inValue.arg0 = arg0;
            return ((ServiceReferenceMESproPanelWs.ICalbWmsGetFinshProPanelWebService)(this)).wmsGetFinishProPanelAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CalbWmsGetFinshProPanelWebServiceImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CalbWmsGetFinshProPanelWebServiceImplPort))
            {
                return new System.ServiceModel.EndpointAddress("http://10.79.5.10:9080/calb_mes/ws/proPanelWs");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CalbWmsGetFinshProPanelWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.CalbWmsGetFinshProPanelWebServiceImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CalbWmsGetFinshProPanelWebServiceClient.GetEndpointAddress(EndpointConfiguration.CalbWmsGetFinshProPanelWebServiceImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            CalbWmsGetFinshProPanelWebServiceImplPort,
        }
    }
}
