//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceMESPolarInfromWs
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wms_get_polar_inform_interface_impl.wms_get_polar_inform_interface.webserv" +
        "ices.calb/", ConfigurationName="ServiceReferenceMESPolarInfromWs.ICalbWmesGetPolarInformWebService")]
    public interface ICalbWmesGetPolarInformWebService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(wmsIfaceResultVO))]
        System.Threading.Tasks.Task<ServiceReferenceMESPolarInfromWs.wmsGetPolarinformResponse> wmsGetPolarinformAsync(ServiceReferenceMESPolarInfromWs.wmsGetPolarinform request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wms_get_polar_inform_interface_impl.wms_get_polar_inform_interface.webserv" +
        "ices.calb/")]
    public partial class calbPolarMtBarCodeVO
    {
        
        private string matBarcodeField;
        
        private string remarks1Field;
        
        private string remarks2Field;
        
        private string remarks3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string matBarcode
        {
            get
            {
                return this.matBarcodeField;
            }
            set
            {
                this.matBarcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string remarks1
        {
            get
            {
                return this.remarks1Field;
            }
            set
            {
                this.remarks1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string remarks2
        {
            get
            {
                return this.remarks2Field;
            }
            set
            {
                this.remarks2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string remarks3
        {
            get
            {
                return this.remarks3Field;
            }
            set
            {
                this.remarks3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wms_get_polar_inform_interface_impl.wms_get_polar_inform_interface.webserv" +
        "ices.calb/")]
    public partial class calbPloarPieceDataVO
    {
        
        private string categoryField;
        
        private string inspectionResultField;
        
        private string lengthField;
        
        private string matBarcodeField;
        
        private string materielCodeField;
        
        private string materielTypeField;
        
        private string ngMessageField;
        
        private string productDateField;
        
        private string productOrderField;
        
        private string productSignField;
        
        private string productionPlanNoField;
        
        private string remarks1Field;
        
        private string remarks2Field;
        
        private string remarks3Field;
        
        private string remarks4Field;
        
        private string remarks5Field;
        
        private string remarks6Field;
        
        private string responsibleField;
        
        private string sectionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string inspectionResult
        {
            get
            {
                return this.inspectionResultField;
            }
            set
            {
                this.inspectionResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string length
        {
            get
            {
                return this.lengthField;
            }
            set
            {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string matBarcode
        {
            get
            {
                return this.matBarcodeField;
            }
            set
            {
                this.matBarcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string materielCode
        {
            get
            {
                return this.materielCodeField;
            }
            set
            {
                this.materielCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string materielType
        {
            get
            {
                return this.materielTypeField;
            }
            set
            {
                this.materielTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ngMessage
        {
            get
            {
                return this.ngMessageField;
            }
            set
            {
                this.ngMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string productDate
        {
            get
            {
                return this.productDateField;
            }
            set
            {
                this.productDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string productOrder
        {
            get
            {
                return this.productOrderField;
            }
            set
            {
                this.productOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string productSign
        {
            get
            {
                return this.productSignField;
            }
            set
            {
                this.productSignField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string productionPlanNo
        {
            get
            {
                return this.productionPlanNoField;
            }
            set
            {
                this.productionPlanNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string remarks1
        {
            get
            {
                return this.remarks1Field;
            }
            set
            {
                this.remarks1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string remarks2
        {
            get
            {
                return this.remarks2Field;
            }
            set
            {
                this.remarks2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string remarks3
        {
            get
            {
                return this.remarks3Field;
            }
            set
            {
                this.remarks3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string remarks4
        {
            get
            {
                return this.remarks4Field;
            }
            set
            {
                this.remarks4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string remarks5
        {
            get
            {
                return this.remarks5Field;
            }
            set
            {
                this.remarks5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string remarks6
        {
            get
            {
                return this.remarks6Field;
            }
            set
            {
                this.remarks6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string responsible
        {
            get
            {
                return this.responsibleField;
            }
            set
            {
                this.responsibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string section
        {
            get
            {
                return this.sectionField;
            }
            set
            {
                this.sectionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(calbPolarPieceReceiveResultVO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wms_get_polar_inform_interface_impl.wms_get_polar_inform_interface.webserv" +
        "ices.calb/")]
    public partial class wmsIfaceResultVO
    {
        
        private int codeField;
        
        private string messageField;
        
        private string remarks1Field;
        
        private string remarks2Field;
        
        private string remarks3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string remarks1
        {
            get
            {
                return this.remarks1Field;
            }
            set
            {
                this.remarks1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string remarks2
        {
            get
            {
                return this.remarks2Field;
            }
            set
            {
                this.remarks2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string remarks3
        {
            get
            {
                return this.remarks3Field;
            }
            set
            {
                this.remarks3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wms_get_polar_inform_interface_impl.wms_get_polar_inform_interface.webserv" +
        "ices.calb/")]
    public partial class calbPolarPieceReceiveResultVO : wmsIfaceResultVO
    {
        
        private calbPloarPieceDataVO dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public calbPloarPieceDataVO data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wmsGetPolarinform", WrapperNamespace="http://wms_get_polar_inform_interface_impl.wms_get_polar_inform_interface.webserv" +
        "ices.calb/", IsWrapped=true)]
    public partial class wmsGetPolarinform
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wms_get_polar_inform_interface_impl.wms_get_polar_inform_interface.webserv" +
            "ices.calb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReferenceMESPolarInfromWs.calbPolarMtBarCodeVO arg0;
        
        public wmsGetPolarinform()
        {
        }
        
        public wmsGetPolarinform(ServiceReferenceMESPolarInfromWs.calbPolarMtBarCodeVO arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wmsGetPolarinformResponse", WrapperNamespace="http://wms_get_polar_inform_interface_impl.wms_get_polar_inform_interface.webserv" +
        "ices.calb/", IsWrapped=true)]
    public partial class wmsGetPolarinformResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wms_get_polar_inform_interface_impl.wms_get_polar_inform_interface.webserv" +
            "ices.calb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReferenceMESPolarInfromWs.calbPolarPieceReceiveResultVO @return;
        
        public wmsGetPolarinformResponse()
        {
        }
        
        public wmsGetPolarinformResponse(ServiceReferenceMESPolarInfromWs.calbPolarPieceReceiveResultVO @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ICalbWmesGetPolarInformWebServiceChannel : ServiceReferenceMESPolarInfromWs.ICalbWmesGetPolarInformWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class CalbWmesGetPolarInformWebServiceClient : System.ServiceModel.ClientBase<ServiceReferenceMESPolarInfromWs.ICalbWmesGetPolarInformWebService>, ServiceReferenceMESPolarInfromWs.ICalbWmesGetPolarInformWebService
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CalbWmesGetPolarInformWebServiceClient() : 
                base(CalbWmesGetPolarInformWebServiceClient.GetDefaultBinding(), CalbWmesGetPolarInformWebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CalbWmesGetPolarInformWebServiceImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalbWmesGetPolarInformWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CalbWmesGetPolarInformWebServiceClient.GetBindingForEndpoint(endpointConfiguration), CalbWmesGetPolarInformWebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public CalbWmesGetPolarInformWebServiceClient(string remoteAddress) :
        base(CalbWmesGetPolarInformWebServiceClient.GetDefaultBinding(), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = EndpointConfiguration.CalbWmesGetPolarInformWebServiceImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public CalbWmesGetPolarInformWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CalbWmesGetPolarInformWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalbWmesGetPolarInformWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CalbWmesGetPolarInformWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalbWmesGetPolarInformWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceMESPolarInfromWs.wmsGetPolarinformResponse> ServiceReferenceMESPolarInfromWs.ICalbWmesGetPolarInformWebService.wmsGetPolarinformAsync(ServiceReferenceMESPolarInfromWs.wmsGetPolarinform request)
        {
            return base.Channel.wmsGetPolarinformAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMESPolarInfromWs.wmsGetPolarinformResponse> wmsGetPolarinformAsync(ServiceReferenceMESPolarInfromWs.calbPolarMtBarCodeVO arg0)
        {
            ServiceReferenceMESPolarInfromWs.wmsGetPolarinform inValue = new ServiceReferenceMESPolarInfromWs.wmsGetPolarinform();
            inValue.arg0 = arg0;
            return ((ServiceReferenceMESPolarInfromWs.ICalbWmesGetPolarInformWebService)(this)).wmsGetPolarinformAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CalbWmesGetPolarInformWebServiceImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CalbWmesGetPolarInformWebServiceImplPort))
            {
                return new System.ServiceModel.EndpointAddress("http://10.79.5.10:9080/calb_mes/ws/polarInfromWs");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CalbWmesGetPolarInformWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.CalbWmesGetPolarInformWebServiceImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CalbWmesGetPolarInformWebServiceClient.GetEndpointAddress(EndpointConfiguration.CalbWmesGetPolarInformWebServiceImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            CalbWmesGetPolarInformWebServiceImplPort,
        }
    }
}
