//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ServiceModel;

namespace ServiceReferenceLES
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://interface.hzero.org/v1/", ConfigurationName="ServiceReferenceLES.ApiSoapInvokeController")]
    public interface ApiSoapInvokeController
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invokeBindWSDLResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invokeBindWSDL))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invokeForPublicResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invokeForPublic))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invokeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invoke))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(httpEntity))]
  
        System.Threading.Tasks.Task<ServiceReferenceLES.invokeResponse1> invokeAsync(ServiceReferenceLES.invoke1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invokeBindWSDLResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invokeBindWSDL))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invokeForPublicResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invokeForPublic))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invokeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invoke))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(httpEntity))]
        System.Threading.Tasks.Task<ServiceReferenceLES.invokeForPublicResponse1> invokeForPublicAsync(ServiceReferenceLES.invokeForPublic1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invokeBindWSDLResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invokeBindWSDL))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invokeForPublicResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invokeForPublic))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invokeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(invoke))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(httpEntity))]
        System.Threading.Tasks.Task<ServiceReferenceLES.invokeBindWSDLResponse1> invokeBindWSDLAsync(ServiceReferenceLES.invokeBindWSDL1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interface.hzero.org/v1/")]
    public partial class requestPayloadDTO
    {
        
        private dataEntry[] headerParamMapField;
        
        private dataEntry[] pathVariableMapField;
        
        private dataEntry[] requestParamMapField;
        
        private dataEntry[] bodyParamMapField;
        
        private string mediaTypeField;
        
        private string payloadField;
        
        private string retrySourceBatchNumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataEntryList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dataEntry[] headerParamMap
        {
            get
            {
                return this.headerParamMapField;
            }
            set
            {
                this.headerParamMapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataEntryList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dataEntry[] pathVariableMap
        {
            get
            {
                return this.pathVariableMapField;
            }
            set
            {
                this.pathVariableMapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataEntryList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dataEntry[] requestParamMap
        {
            get
            {
                return this.requestParamMapField;
            }
            set
            {
                this.requestParamMapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dataEntryList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dataEntry[] bodyParamMap
        {
            get
            {
                return this.bodyParamMapField;
            }
            set
            {
                this.bodyParamMapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string mediaType
        {
            get
            {
                return this.mediaTypeField;
            }
            set
            {
                this.mediaTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string payload
        {
            get
            {
                return this.payloadField;
            }
            set
            {
                this.payloadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string retrySourceBatchNum
        {
            get
            {
                return this.retrySourceBatchNumField;
            }
            set
            {
                this.retrySourceBatchNumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interface.hzero.org/v1/")]
    public partial class dataEntry
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interface.hzero.org/v1/")]
    public partial class invokeBindWSDLResponse
    {
        
        private responsePayloadDTO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public responsePayloadDTO @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interface.hzero.org/v1/")]
    public partial class responsePayloadDTO : responseEntity
    {
        
        private apiInfo apiInfoField;
        
        private string batchNumField;
        
        private interfaceContextDTO interfaceContextField;
        
        private string invokeKeyField;
        
        private string mediaTypeField;
        
        private string messageField;
        
        private string payloadField;
        
        private string statusField;
        
        private responsePayloadDTOEntry[] targetResponseHeadersField;
        
        private string traceKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public apiInfo apiInfo
        {
            get
            {
                return this.apiInfoField;
            }
            set
            {
                this.apiInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string batchNum
        {
            get
            {
                return this.batchNumField;
            }
            set
            {
                this.batchNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public interfaceContextDTO interfaceContext
        {
            get
            {
                return this.interfaceContextField;
            }
            set
            {
                this.interfaceContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string invokeKey
        {
            get
            {
                return this.invokeKeyField;
            }
            set
            {
                this.invokeKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string mediaType
        {
            get
            {
                return this.mediaTypeField;
            }
            set
            {
                this.mediaTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string payload
        {
            get
            {
                return this.payloadField;
            }
            set
            {
                this.payloadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public responsePayloadDTOEntry[] targetResponseHeaders
        {
            get
            {
                return this.targetResponseHeadersField;
            }
            set
            {
                this.targetResponseHeadersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string traceKey
        {
            get
            {
                return this.traceKeyField;
            }
            set
            {
                this.traceKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interface.hzero.org/v1/")]
    public partial class apiInfo
    {
        
        private string apiStatusField;
        
        private string apiVersionField;
        
        private string apiWarningsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apiStatus
        {
            get
            {
                return this.apiStatusField;
            }
            set
            {
                this.apiStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apiVersion
        {
            get
            {
                return this.apiVersionField;
            }
            set
            {
                this.apiVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string apiWarnings
        {
            get
            {
                return this.apiWarningsField;
            }
            set
            {
                this.apiWarningsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interface.hzero.org/v1/")]
    public partial class interfaceContextDTO
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://interface.hzero.org/v1/")]
    public partial class responsePayloadDTOEntry
    {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(responsePayloadDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interface.hzero.org/v1/")]
    public partial class responseEntity : httpEntity
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(responseEntity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(responsePayloadDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interface.hzero.org/v1/")]
    public partial class httpEntity
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interface.hzero.org/v1/")]
    public partial class invokeBindWSDL
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interface.hzero.org/v1/")]
    public partial class invokeForPublicResponse
    {
        
        private responsePayloadDTO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public responsePayloadDTO @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interface.hzero.org/v1/")]
    public partial class invokeForPublic
    {
        
        private string namespaceField;
        
        private string serverCodeField;
        
        private string interfaceCodeField;
        
        private requestPayloadDTO payloadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @namespace
        {
            get
            {
                return this.namespaceField;
            }
            set
            {
                this.namespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string serverCode
        {
            get
            {
                return this.serverCodeField;
            }
            set
            {
                this.serverCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string interfaceCode
        {
            get
            {
                return this.interfaceCodeField;
            }
            set
            {
                this.interfaceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public requestPayloadDTO payload
        {
            get
            {
                return this.payloadField;
            }
            set
            {
                this.payloadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interface.hzero.org/v1/")]
    public partial class invokeResponse
    {
        
        private responsePayloadDTO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public responsePayloadDTO @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interface.hzero.org/v1/")]
    public partial class invoke
    {
        
        private string namespaceField;
        
        private string serverCodeField;
        
        private string interfaceCodeField;
        
        private requestPayloadDTO payloadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @namespace
        {
            get
            {
                return this.namespaceField;
            }
            set
            {
                this.namespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string serverCode
        {
            get
            {
                return this.serverCodeField;
            }
            set
            {
                this.serverCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string interfaceCode
        {
            get
            {
                return this.interfaceCodeField;
            }
            set
            {
                this.interfaceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public requestPayloadDTO payload
        {
            get
            {
                return this.payloadField;
            }
            set
            {
                this.payloadField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="invoke", WrapperNamespace="http://interface.hzero.org/v1/", IsWrapped=true)]
    public partial class invoke1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interface.hzero.org/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @namespace;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interface.hzero.org/v1/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serverCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interface.hzero.org/v1/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string interfaceCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interface.hzero.org/v1/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReferenceLES.requestPayloadDTO payload;
        
        public invoke1()
        {
        }
        
        public invoke1(string @namespace, string serverCode, string interfaceCode, ServiceReferenceLES.requestPayloadDTO payload)
        {
            this.@namespace = @namespace;
            this.serverCode = serverCode;
            this.interfaceCode = interfaceCode;
            this.payload = payload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="invokeResponse", WrapperNamespace="http://interface.hzero.org/v1/", IsWrapped=true)]
    public partial class invokeResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interface.hzero.org/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReferenceLES.responsePayloadDTO @return;
        
        public invokeResponse1()
        {
        }
        
        public invokeResponse1(ServiceReferenceLES.responsePayloadDTO @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="invokeForPublic", WrapperNamespace="http://interface.hzero.org/v1/", IsWrapped=true)]
    public partial class invokeForPublic1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interface.hzero.org/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @namespace;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interface.hzero.org/v1/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serverCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interface.hzero.org/v1/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string interfaceCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interface.hzero.org/v1/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReferenceLES.requestPayloadDTO payload;
        
        public invokeForPublic1()
        {
        }
        
        public invokeForPublic1(string @namespace, string serverCode, string interfaceCode, ServiceReferenceLES.requestPayloadDTO payload)
        {
            this.@namespace = @namespace;
            this.serverCode = serverCode;
            this.interfaceCode = interfaceCode;
            this.payload = payload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="invokeForPublicResponse", WrapperNamespace="http://interface.hzero.org/v1/", IsWrapped=true)]
    public partial class invokeForPublicResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interface.hzero.org/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReferenceLES.responsePayloadDTO @return;
        
        public invokeForPublicResponse1()
        {
        }
        
        public invokeForPublicResponse1(ServiceReferenceLES.responsePayloadDTO @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="invokeBindWSDL", WrapperNamespace="http://interface.hzero.org/v1/", IsWrapped=true)]
    public partial class invokeBindWSDL1
    {
        
        public invokeBindWSDL1()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="invokeBindWSDLResponse", WrapperNamespace="http://interface.hzero.org/v1/", IsWrapped=true)]
    public partial class invokeBindWSDLResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interface.hzero.org/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReferenceLES.responsePayloadDTO @return;
        
        public invokeBindWSDLResponse1()
        {
        }
        
        public invokeBindWSDLResponse1(ServiceReferenceLES.responsePayloadDTO @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ApiSoapInvokeControllerChannel : ServiceReferenceLES.ApiSoapInvokeController, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ApiSoapInvokeControllerClient : System.ServiceModel.ClientBase<ServiceReferenceLES.ApiSoapInvokeController>, ServiceReferenceLES.ApiSoapInvokeController
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ApiSoapInvokeControllerClient() : 
                base(ApiSoapInvokeControllerClient.GetDefaultBinding(), ApiSoapInvokeControllerClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ApiSoapInvokeControllerPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

  


        public ApiSoapInvokeControllerClient(string remoteAddress) :
        base(ApiSoapInvokeControllerClient.GetDefaultBinding(), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
           

            this.Endpoint.Name = EndpointConfiguration.ApiSoapInvokeControllerPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ApiSoapInvokeControllerClient(EndpointConfiguration endpointConfiguration) : 
                base(ApiSoapInvokeControllerClient.GetBindingForEndpoint(endpointConfiguration), ApiSoapInvokeControllerClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApiSoapInvokeControllerClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ApiSoapInvokeControllerClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApiSoapInvokeControllerClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ApiSoapInvokeControllerClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApiSoapInvokeControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceLES.invokeResponse1> ServiceReferenceLES.ApiSoapInvokeController.invokeAsync(ServiceReferenceLES.invoke1 request)
        {
            return base.Channel.invokeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceLES.invokeResponse1> invokeAsync(string @namespace, string serverCode, string interfaceCode, ServiceReferenceLES.requestPayloadDTO payload)
        {
            ServiceReferenceLES.invoke1 inValue = new ServiceReferenceLES.invoke1();
            inValue.@namespace = @namespace;
            inValue.serverCode = serverCode;
            inValue.interfaceCode = interfaceCode;
            inValue.payload = payload;
            return ((ServiceReferenceLES.ApiSoapInvokeController)(this)).invokeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceLES.invokeForPublicResponse1> ServiceReferenceLES.ApiSoapInvokeController.invokeForPublicAsync(ServiceReferenceLES.invokeForPublic1 request)
        {
            return base.Channel.invokeForPublicAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceLES.invokeForPublicResponse1> invokeForPublicAsync(string @namespace, string serverCode, string interfaceCode, ServiceReferenceLES.requestPayloadDTO payload)
        {
            ServiceReferenceLES.invokeForPublic1 inValue = new ServiceReferenceLES.invokeForPublic1();
            inValue.@namespace = @namespace;
            inValue.serverCode = serverCode;
            inValue.interfaceCode = interfaceCode;
            inValue.payload = payload;
            return ((ServiceReferenceLES.ApiSoapInvokeController)(this)).invokeForPublicAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceLES.invokeBindWSDLResponse1> ServiceReferenceLES.ApiSoapInvokeController.invokeBindWSDLAsync(ServiceReferenceLES.invokeBindWSDL1 request)
        {
            return base.Channel.invokeBindWSDLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceLES.invokeBindWSDLResponse1> invokeBindWSDLAsync()
        {
            ServiceReferenceLES.invokeBindWSDL1 inValue = new ServiceReferenceLES.invokeBindWSDL1();
            return ((ServiceReferenceLES.ApiSoapInvokeController)(this)).invokeBindWSDLAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ApiSoapInvokeControllerPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ApiSoapInvokeControllerPort))
            {
                return new System.ServiceModel.EndpointAddress("http://10.79.5.14:30080/hitf/v1/soap/invoke");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ApiSoapInvokeControllerClient.GetBindingForEndpoint(EndpointConfiguration.ApiSoapInvokeControllerPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ApiSoapInvokeControllerClient.GetEndpointAddress(EndpointConfiguration.ApiSoapInvokeControllerPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ApiSoapInvokeControllerPort,
        }
    }
}
